// AUTOGENERATED
using Fu.Steps;

namespace Fu
{
	namespace Steps
	{
		public interface ICompressSteps { }
		public interface IHttpSteps { }
		public interface IMapSteps { }
		public interface IRenderSteps { }
		public interface IRedirectSteps { }
		public interface IStaticSteps { }
		public interface IWalksSteps { }
	}

	public static partial class fu
    {
		// Extension points to "park" the extension methods in
		// on the fu class, these interfaces serve no other puposes
		// and should and always will be left null
		public static ICompressSteps Compress { get { return null; } }
		public static IHttpSteps Http { get { return null; } }
		public static IMapSteps Map { get { return null; } }
		public static IRenderSteps Render { get { return null; } }
		public static IRedirectSteps Redirect { get { return null; } }
		public static IStaticSteps Static { get { return null; } }
		public static IWalksSteps Walks { get { return null; } }
    }
}
